title: "欢迎光临"
content: "Shirone 内容与配置分离测试站点已接入官方完整示例数据与 Markdown 扩展生态！"
text: "Shirone 内容与配置分离测试站点已接入官方完整示例数据与 Markdown 扩展生态！"
icon: "material-symbols:campaign-outline-rounded"
type: "info"
closable: true
closeDuration: 86400
link:
  enable: true
  text: "查看说明"
  url: "/about/"
  external: false
