lastUpdated:
  enable: true
  minimumAgeDays: 180
discovery:
  enable: true
  related:
    enable: true
    count: 4
  random:
    enable: true
    count: 4
share:
  enable: true
  includeCover: true
