enable: true
provider: "twikoo"
lazy: true
twikoo:
  envId: "https://twikoo-test.example.com"
  scriptUrl: "https://cdn.jsdelivr.net/npm/twikoo@1.6.41/dist/twikoo.all.min.js"
  lang: "auto"
  placeholder: "欢迎留下友善的评论..."
