enable: true
align: "end"
offset:
  bottom: "2rem"
  right: "2rem"
size: "regular"
items:
  - type: "top"
    enable: true
    devices:
      - "mobile"
      - "tablet"
      - "desktop"
    pages: []
    scrollThresholdRatio: 0.3
  - type: "toc"
    enable: true
    devices:
      - "mobile"
    pages:
      - "post"
    depth: 3
    closeOnSelect: true
  - type: "comment"
    enable: true
    devices:
      - "mobile"
      - "tablet"
      - "desktop"
    pages:
      - "post"
    targetSelector: "#comment-container"
  - type: "home"
    enable: true
    devices:
      - "mobile"
      - "tablet"
      - "desktop"
    pages: []
    onlySubPages: true
