avatar: "assets/images/demo-avatar.webp"
name: "Shirone"
bio: "A Material 3 anime blog theme based on Astro & Svelte"
links:
  - name: "GitHub"
    icon: "fa6-brands:github"
    url: "https://github.com/LyraVoid/Shirone"
  - name: "Twitter"
    icon: "fa6-brands:x-twitter"
    url: "https://x.com"
  - name: "Bilibili"
    icon: "fa6-brands:bilibili"
    url: "https://bilibili.com"
  - name: "Steam"
    icon: "fa6-brands:steam"
    url: "https://store.steampowered.com"
