enable: true
categories:
  - key: "theme"
    label: "开源主题"
    icon: "material-symbols:palette-outline-rounded"
  - key: "app"
    label: "独立应用"
    icon: "material-symbols:apps-rounded"
  - key: "tool"
    label: "效率工具"
    icon: "material-symbols:build-outline-rounded"
disabledKeys: []
