enable: true
arrangement: "dual"
side: "left"
components:
  - type: "profile"
    enable: true
    slot: "top"
  - type: "music"
    enable: true
    slot: "top"
  - type: "announcement"
    enable: true
    slot: "top"
    pages:
      - "home"
  - type: "categories"
    enable: true
    slot: "sticky"
    collapseAfter: 5
  - type: "tags"
    enable: true
    slot: "sticky"
    collapseAfter: 6
  - type: "stats"
    enable: true
    slot: "top"
    column: "secondary"
    pages:
      - "home"
      - "archive"
      - "categories"
      - "tags"
  - type: "calendar"
    enable: true
    slot: "top"
    column: "secondary"
  - type: "toc"
    enable: true
    slot: "sticky"
    column: "secondary"
    pages:
      - "post"
