enable: true
categories:
  - key: "frontend"
    label: "前端开发"
    icon: "material-symbols:web-rounded"
  - key: "backend"
    label: "后端工程"
    icon: "material-symbols:dns-rounded"
  - key: "devops"
    label: "云原生与运维"
    icon: "material-symbols:cloud-done-outline-rounded"
disabledNames: []
