enable: true
categories:
  - key: "milestone"
    label: "里程碑"
    icon: "material-symbols:flag-rounded"
  - key: "project"
    label: "项目发布"
    icon: "material-symbols:code-rounded"
  - key: "life"
    label: "日常记录"
    icon: "material-symbols:favorite-rounded"
order: "desc"
disabledTitles: []
